


version: "3.9"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    environment:
      - PORT=5000
      - GEMINI_API_KEY=AIzaSyDcNIK0uTX0nHgjrgS9OGym7BQD0Ym7dHw
      - CORS_ORIGIN=http://localhost:5173
    command: ["npm", "start"]

